- name: HACS Action
  # You may pin to the exact commit or the version.
  # uses: hacs/action@6bd83b3d810cec917099701fa1de18ac584e694a
  uses: hacs/action@21.12.1
  with:
    # A space seperated list of ignored checks, for valid entries see README.md
    ignore: # optional, default is 
    # The category of repository
    category: integration
    # The full name of repository
    repository: # optional
    # Post a comment to the PR with the result of the checks
    comment: true # optional, default is true
